name: Generate Repository Summary Data

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 1 * *'  # Run at midnight on the 1st day of every month
  workflow_dispatch: 

jobs:
  generate-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Generate Repository Summary
      uses: matmulai/generator@v1.1
      with:
        # Configure any options needed for the action
        github_token: ${{ secrets.GITHUB_TOKEN }}
        output_file: _data/generated_data.csv
        
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add _data/generated_data.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update repository summary data" && git push)
