name: Generate Data and Build Jekyll Site
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 1 * *'  # Monthly update
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 1: Generate the repository data
      - name: Create data directory
        run: mkdir -p _data
      
      - name: Generate Repository Summaries
        uses: gojiplus/generator@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          org_name: matmulai
          openai_api_key: ${{ secrets.MY_OPENAI_API_KEY }}
      
      - name: Copy output file
        run: cp -v repo_summaries.json _data/generated_data.json

      # Step 2: Build and deploy the Jekyll site
      - name: Build and deploy
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: gh-pages
