name: Generate Repository Summary Data
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:
  generate-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          # Add this to fetch all history for proper merging
          fetch-depth: 0
      
      - name: Create data directory
        run: |
          # Create _data directory with exact name (no asterisks)
          mkdir -p _data
          echo "Created _data directory"
      
      - name: Generate Repository Summaries
        uses: gojiplus/generator@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          org_name: matmulai
          openai_api_key: ${{ secrets.MY_OPENAI_API_KEY }}
      
      - name: Copy output file
        run: |
          # Copy to the proper directory (no asterisks)
          cp -v repo_summaries.json _data/generated_data.json
      
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Pull latest changes first to resolve conflicts
          git pull origin main
          
          # Add the file with proper path (no asterisks)
          git add _data/generated_data.json
          
          # Commit and push with conflict resolution
          git diff --staged --quiet || git commit -m "Auto-update repository summary data"
          git push
