name: Generate Repository Summary Data
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 1 * *'  # Run at midnight on the 1st day of every month
  workflow_dispatch:
jobs:
  generate-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for pushing changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
      
      - name: Ensure _data folder exists
        run: mkdir -p _data
      
      - name: Generate Repository Summaries
        uses: gojiplus/generator@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          org_name: matmulai
          openai_api_key: ${{ secrets.MY_OPENAI_API_KEY }}
      
      - name: Move output file to data directory
        run: |
          # Assuming your action generates repo_summaries.json in the working directory
          mv repo_summaries.json _data/generated_data.json || echo "No output file found"
      
      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add _data/generated_data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update repository summary data" && git push)
          
